#ifndef PhotonEfficiencySF_h
#define PhotonEfficiencySF_h


#include "Utils.h"
// cf.
// https://twiki.cern.ch/twiki/bin/viewauth/CMS/EgammaIDRecipesRun2 
//
class PhotonEfficiencySF
{
  public:
    //
    PhotonEfficiencySF() { }

    //
    ~PhotonEfficiencySF() {}

    //
    std::pair<float,float> getPhotonEfficiency(float pt, float superClusterEta, std::string wp, int cutVersion){
      std::pair<float,float> eff(1.0,0.00);
      std::pair<float, float> eff_PixelVeto(1.0, 0.00);

      switch(cutVersion){
        case utils::CutVersion::Moriond17Cut :
          //Photon SF (from: https://indico.cern.ch/event/604907/contributions/2452908/attachments/1401556/2139396/01_25_EGM.pdf)
          if(wp == "tight"){
            if(superClusterEta >= -2.5 && superClusterEta < -2){
	            if(pt >= 20 && pt < 35){ eff.first=0.902801; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 35 && pt < 50){ eff.first=0.916176; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 50 && pt < 90){ eff.first=0.921016; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 90 && pt < 150){ eff.first=0.940111; eff.second=0.00; //Error is not in the file...
	            }else{ eff.first=0.940111; eff.second=0.00; //Error is not in the file...
	            }
            }else if(superClusterEta >= -2 && superClusterEta < -1.566){
	            if(pt >= 20 && pt < 35){ eff.first=0.942149; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 35 && pt < 50){ eff.first=0.957227; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 50 && pt < 90){ eff.first=0.962697; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 90 && pt < 150){ eff.first=0.988636; eff.second=0.00; //Error is not in the file...
	            }else{ eff.first=0.988636; eff.second=0.00; //Error is not in the file...
	            }
            }else if(superClusterEta >= -1.566 && superClusterEta < -1.444){
	            if(pt >= 20 && pt < 35){ eff.first=1; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 35 && pt < 50){ eff.first=1; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 50 && pt < 90){ eff.first=1; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 90 && pt < 150){ eff.first=1; eff.second=0.00; //Error is not in the file...
	            }else{ eff.first=1; eff.second=0.00; //Error is not in the file...
	            }
            }else if(superClusterEta >= -1.444 && superClusterEta < -0.8){
	            if(pt >= 20 && pt < 35){ eff.first=0.980424; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 35 && pt < 50){ eff.first=0.977143; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 50 && pt < 90){ eff.first=0.968011; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 90 && pt < 150){ eff.first=1.01124; eff.second=0.00; //Error is not in the file...
	            }else{ eff.first=1.01124; eff.second=0.00; //Error is not in the file...
	            }
            }else if(superClusterEta >= -0.8 && superClusterEta < 0){
	            if(pt >= 20 && pt < 35){ eff.first=0.968696; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 35 && pt < 50){ eff.first=0.963018; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 50 && pt < 90){ eff.first=0.952654; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 90 && pt < 150){ eff.first=0.998553; eff.second=0.00; //Error is not in the file...
	            }else{ eff.first=0.998553; eff.second=0.00; //Error is not in the file...
	            }
            }else if(superClusterEta >= 0 && superClusterEta < 0.8){
	            if(pt >= 20 && pt < 35){ eff.first=0.98594; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 35 && pt < 50){ eff.first=0.980539; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 50 && pt < 90){ eff.first=0.970972; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 90 && pt < 150){ eff.first=1.0073; eff.second=0.00; //Error is not in the file...
	            }else{ eff.first=1.0073; eff.second=0.00; //Error is not in the file...
	            }
            }else if(superClusterEta >= 0.8 && superClusterEta < 1.444){
	            if(pt >= 20 && pt < 35){ eff.first=0.990083; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 35 && pt < 50){ eff.first=0.979885; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 50 && pt < 90){ eff.first=0.97067; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 90 && pt < 150){ eff.first=1.02553; eff.second=0.00; //Error is not in the file...
	            }else{ eff.first=1.02553; eff.second=0.00; //Error is not in the file...
	            }
            }else if(superClusterEta >= 1.444 && superClusterEta < 1.566){
	            if(pt >= 20 && pt < 35){ eff.first=1; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 35 && pt < 50){ eff.first=1; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 50 && pt < 90){ eff.first=1; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 90 && pt < 150){ eff.first=1; eff.second=0.00; //Error is not in the file...
	            }else{ eff.first=1; eff.second=0.00; //Error is not in the file...
	            }
            }else if(superClusterEta >= 1.566 && superClusterEta < 2){
	            if(pt >= 20 && pt < 35){ eff.first=0.936667; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 35 && pt < 50){ eff.first=0.956909; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 50 && pt < 90){ eff.first=0.94835; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 90 && pt < 150){ eff.first=0.983027; eff.second=0.00; //Error is not in the file...
	            }else{ eff.first=0.983027; eff.second=0.00; //Error is not in the file...
	            }
            }else if(superClusterEta >= 2 && superClusterEta < 2.5){
	            if(pt >= 20 && pt < 35){ eff.first=0.903974; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 35 && pt < 50){ eff.first=0.9273; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 50 && pt < 90){ eff.first=0.931721; eff.second=0.00; //Error is not in the file...
	            }else if(pt >= 90 && pt < 150){ eff.first=0.982759; eff.second=0.00; //Error is not in the file...
	            }else{ eff.first=0.982759; eff.second=0.00; //Error is not in the file...
	            }
            }
          }
          //Pixel Veto SF (from https://twiki.cern.ch/twiki/pub/CMS/EgammaIDRecipesRun2/EleVetoScalingFactors_Moriond17.pdf)
          if(fabs(superClusterEta) >= 0 && fabs(superClusterEta) < 1.444){ eff_PixelVeto.first=0.9978; eff_PixelVeto.second=0.0134;}
          else if(fabs(superClusterEta) >= 1.566 && fabs(superClusterEta) < 2.5){ eff_PixelVeto.first=0.9931; eff_PixelVeto.second=0.0245;}

          break;
      }
      eff.first = eff.first*eff_PixelVeto.first;
      eff.second = sqrt(eff.second*eff.second+eff_PixelVeto.second*eff_PixelVeto.second);
      return eff;
    }

  private:

};


#endif

